# Generated by Django 5.0.1 on 2024-03-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_levelofeducation_student_level_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelofeducation',
            name='level',
            field=models.CharField(max_length=50, verbose_name='Level of Education'),
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('email', models.EmailField(max_length=277, verbose_name='Student Email')),
                ('level_of_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudapp.levelofeducation', verbose_name='Level of Education')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
